// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20231030144706_Add Animal Status")]
    partial class AddAnimalStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Experiences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 700, DateTimeKind.Local).AddTicks(2653),
                            Fullname = "Lion Tamer",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 700, DateTimeKind.Local).AddTicks(2663),
                            Password = "WaAgEP5BIxkAWtYKnswysi09PA86oZN4IaWi9V+F2vCWx3m/",
                            Role = 1,
                            Username = "LionTamer"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 706, DateTimeKind.Local).AddTicks(6535),
                            Fullname = "Pachyderm Pro",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 706, DateTimeKind.Local).AddTicks(6548),
                            Password = "Kx2nr+ukOYqlrAPdYKYR19YHz1He0d5Eak9byA+UFqSjtYF0",
                            Role = 1,
                            Username = "PachydermPro"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 713, DateTimeKind.Local).AddTicks(2262),
                            Fullname = "Shark Whisperer",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 713, DateTimeKind.Local).AddTicks(2282),
                            Password = "Rh9e4zeu+wq8cEU4O6JviLWB+4scpHsY7CRLT6cQJa7Z1F+v",
                            Role = 1,
                            Username = "SharkWhisperer"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 718, DateTimeKind.Local).AddTicks(5497),
                            Fullname = "Fox Friend",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 718, DateTimeKind.Local).AddTicks(5510),
                            Password = "Co/8e0MrrgzoPZl1NbJjSd0y3bZlNRy1JlMaEcf+FwNqqjCb",
                            Role = 1,
                            Username = "FoxFriend"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 722, DateTimeKind.Local).AddTicks(5723),
                            Fullname = "Penguin Pal",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 722, DateTimeKind.Local).AddTicks(5724),
                            Password = "H86XctIrWSLyrqM3ePy2y83DocD2JPedkZ6fqn/9TZlP47Tf",
                            Role = 1,
                            Username = "PenguinPal"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 726, DateTimeKind.Local).AddTicks(6436),
                            Fullname = "Nhân viên sở thú",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 726, DateTimeKind.Local).AddTicks(6437),
                            Password = "iuQ5AZbt/wbr7Rp3MZu9bEwlXfUeFrypN9mmq1+mqYtEnzm2",
                            Role = 0,
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("Domain.Entities.AnimalInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("AnimalInformations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2018, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4299),
                            Description = "Majestic African lion named Simba.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4313),
                            Name = "Simba",
                            SpeciesId = 1,
                            Status = 1,
                            Weight = 180.0
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2015, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4404),
                            Description = "Gentle Asian elephant named Dumbo.",
                            Height = 10.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4405),
                            Name = "Dumbo",
                            SpeciesId = 2,
                            Status = 1,
                            Weight = 4500.0
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2017, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4413),
                            Description = "Fearsome great white shark named Jaws.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4414),
                            Name = "Jaws",
                            SpeciesId = 3,
                            Status = 1,
                            Weight = 2000.0
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4490),
                            Description = "Cunning European red fox named Foxy.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4491),
                            Name = "Foxy",
                            SpeciesId = 4,
                            Status = 1,
                            Weight = 10.0
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4499),
                            Description = "Regal emperor penguin named Emmy.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4500),
                            Name = "Emmy",
                            SpeciesId = 5,
                            Status = 1,
                            Weight = 35.0
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2017, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4506),
                            Description = "Energetic kangaroo named Kang.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4506),
                            Name = "Kang",
                            SpeciesId = 6,
                            Status = 1,
                            Weight = 70.0
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2016, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4512),
                            Description = "Majestic grizzly bear named Bear.",
                            Height = 5.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4512),
                            Name = "Bear",
                            SpeciesId = 7,
                            Status = 1,
                            Weight = 800.0
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2015, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4518),
                            Description = "Proud polar bear named Nanook.",
                            Height = 4.5,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4519),
                            Name = "Nanook",
                            SpeciesId = 8,
                            Status = 1,
                            Weight = 900.0
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2016, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4527),
                            Description = "Fierce Bengal tiger named Raja.",
                            Height = 3.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4527),
                            Name = "Raja",
                            SpeciesId = 9,
                            Status = 1,
                            Weight = 200.0
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(2017, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4533),
                            Description = "Adorable panda named Pandy.",
                            Height = 2.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4534),
                            Name = "Pandy",
                            SpeciesId = 10,
                            Status = 1,
                            Weight = 150.0
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4539),
                            Description = "Graceful African lioness named Zara.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4540),
                            Name = "Zara",
                            SpeciesId = 1,
                            Status = 1,
                            Weight = 150.0
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(2016, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4546),
                            Description = "Gentle Asian elephant named Babar.",
                            Height = 9.5,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4546),
                            Name = "Babar",
                            SpeciesId = 2,
                            Status = 1,
                            Weight = 4000.0
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(2018, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4553),
                            Description = "Majestic great white shark named Fins.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4553),
                            Name = "Fins",
                            SpeciesId = 3,
                            Status = 1,
                            Weight = 1800.0
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2021, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4559),
                            Description = "Clever European red fox named Sly.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4559),
                            Name = "Sly",
                            SpeciesId = 4,
                            Status = 1,
                            Weight = 12.0
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(2020, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4565),
                            Description = "Charming emperor penguin named Waddle.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4566),
                            Name = "Waddle",
                            SpeciesId = 5,
                            Status = 1,
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(2017, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4571),
                            Description = "Energetic kangaroo named Joey.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4572),
                            Name = "Joey",
                            SpeciesId = 6,
                            Status = 1,
                            Weight = 75.0
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4577),
                            Description = "Playful grizzly bear cub named Bearly.",
                            Height = 2.5,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4578),
                            Name = "Bearly",
                            SpeciesId = 7,
                            Status = 1,
                            Weight = 150.0
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4584),
                            Description = "Young polar bear named Snowy.",
                            Height = 3.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4584),
                            Name = "Snowy",
                            SpeciesId = 8,
                            Status = 1,
                            Weight = 300.0
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4590),
                            Description = "Adventurous Bengal tiger cub named Tyga.",
                            Height = 2.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4591),
                            Name = "Tyga",
                            SpeciesId = 9,
                            Status = 1,
                            Weight = 50.0
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(2019, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4596),
                            Description = "Bamboo-loving panda named Bamboo.",
                            Height = 1.5,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(4597),
                            Name = "Bamboo",
                            SpeciesId = 10,
                            Status = 1,
                            Weight = 120.0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            Code = "A",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(7387),
                            Description = "An exhibit featuring animals from the African savanna",
                            IsDeleted = false,
                            Location = "Savanna Exhibit",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(7389),
                            Name = "African Savanna"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 80,
                            Code = "B",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(7392),
                            Description = "A lush and diverse rainforest habitat",
                            IsDeleted = false,
                            Location = "Rainforest Pavilion",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(7392),
                            Name = "Rainforest"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 50,
                            Code = "C",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(7394),
                            Description = "A cold and watery habitat for penguins",
                            IsDeleted = false,
                            Location = "Aquatic Pavilion",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(7394),
                            Name = "Penguin Cove"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 60,
                            Code = "D",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(7396),
                            Description = "A hot and arid desert environment",
                            IsDeleted = false,
                            Location = "Desert Exhibit",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(7397),
                            Name = "Desert Oasis"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 70,
                            Code = "E",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(7398),
                            Description = "A vibrant coral reef with colorful fish",
                            IsDeleted = false,
                            Location = "Aquatic Pavilion",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(7399),
                            Name = "Tropical Reef"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Cages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            Capacity = 10,
                            Code = "A0001",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9023),
                            Description = "A spacious exhibit featuring African animals.",
                            IsDeleted = false,
                            Location = "Savannah Exhibit",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9027),
                            Name = "African Safari"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            Capacity = 15,
                            Code = "A0002",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9030),
                            Description = "A dedicated area for Asian elephants.",
                            IsDeleted = false,
                            Location = "Asian Elephant Pavilion",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9030),
                            Name = "Elephant Sanctuary"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 2,
                            Capacity = 12,
                            Code = "B0003",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9032),
                            Description = "A large tank showcasing great white sharks.",
                            IsDeleted = false,
                            Location = "Marine World",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9033),
                            Name = "Shark Tank"
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 2,
                            Capacity = 20,
                            Code = "B0004",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9035),
                            Description = "A natural habitat for grizzly bears.",
                            IsDeleted = false,
                            Location = "North American Habitat",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9035),
                            Name = "Grizzly Wilderness"
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 3,
                            Capacity = 8,
                            Code = "C0005",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9037),
                            Description = "A chilly paradise for emperor penguins.",
                            IsDeleted = false,
                            Location = "Antarctic Exhibit",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9038),
                            Name = "Penguin Paradise"
                        },
                        new
                        {
                            Id = 6,
                            AreaId = 1,
                            Capacity = 20,
                            Code = "A0006",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9039),
                            Description = "A vast exhibit showcasing African wildlife.",
                            IsDeleted = false,
                            Location = "Wide Open Savannah",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9040),
                            Name = "African Plains"
                        },
                        new
                        {
                            Id = 7,
                            AreaId = 2,
                            Capacity = 18,
                            Code = "B0007",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9042),
                            Description = "A chilly environment for polar animals.",
                            IsDeleted = false,
                            Location = "Arctic Enclosure",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9042),
                            Name = "Polar Icecaps"
                        },
                        new
                        {
                            Id = 8,
                            AreaId = 3,
                            Capacity = 12,
                            Code = "C0008",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9044),
                            Description = "An arid landscape for Australian fauna.",
                            IsDeleted = false,
                            Location = "Australian Habitat",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9045),
                            Name = "Aussie Outback"
                        },
                        new
                        {
                            Id = 9,
                            AreaId = 4,
                            Capacity = 15,
                            Code = "D0009",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9046),
                            Description = "A dense forest for Siberian wildlife.",
                            IsDeleted = false,
                            Location = "Russian Wilderness",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9047),
                            Name = "Siberian Taiga"
                        },
                        new
                        {
                            Id = 10,
                            AreaId = 5,
                            Capacity = 25,
                            Code = "E0010",
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9049),
                            Description = "A lush jungle exhibit for Amazon species.",
                            IsDeleted = false,
                            Location = "South American Jungle",
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 731, DateTimeKind.Local).AddTicks(9049),
                            Name = "Amazon Rainforest"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("CageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("CageId");

                    b.ToTable("CageHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            CageId = 1,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2297),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2298),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2295)
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 2,
                            CageId = 2,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2300),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2301),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2300)
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = 3,
                            CageId = 3,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2302),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2303),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2302)
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = 4,
                            CageId = 4,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2305),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2305),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2304)
                        },
                        new
                        {
                            Id = 5,
                            AnimalId = 5,
                            CageId = 5,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2307),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2308),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2306)
                        },
                        new
                        {
                            Id = 6,
                            AnimalId = 6,
                            CageId = 6,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2309),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2310),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2309)
                        },
                        new
                        {
                            Id = 7,
                            AnimalId = 7,
                            CageId = 7,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2312),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2312),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2311)
                        },
                        new
                        {
                            Id = 8,
                            AnimalId = 8,
                            CageId = 8,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2314),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2315),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2313)
                        },
                        new
                        {
                            Id = 9,
                            AnimalId = 9,
                            CageId = 9,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2316),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2317),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2316)
                        },
                        new
                        {
                            Id = 10,
                            AnimalId = 10,
                            CageId = 10,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2319),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2319),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2318)
                        },
                        new
                        {
                            Id = 11,
                            AnimalId = 11,
                            CageId = 1,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2321),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2321),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2320)
                        },
                        new
                        {
                            Id = 12,
                            AnimalId = 12,
                            CageId = 2,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2323),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2324),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2323)
                        },
                        new
                        {
                            Id = 13,
                            AnimalId = 13,
                            CageId = 3,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2325),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2326),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2325)
                        },
                        new
                        {
                            Id = 14,
                            AnimalId = 14,
                            CageId = 4,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2327),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2328),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2327)
                        },
                        new
                        {
                            Id = 15,
                            AnimalId = 15,
                            CageId = 5,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2330),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2330),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2329)
                        },
                        new
                        {
                            Id = 16,
                            AnimalId = 16,
                            CageId = 6,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2332),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2333),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2332)
                        },
                        new
                        {
                            Id = 17,
                            AnimalId = 17,
                            CageId = 7,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2334),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2335),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2334)
                        },
                        new
                        {
                            Id = 18,
                            AnimalId = 18,
                            CageId = 8,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2337),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2337),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2336)
                        },
                        new
                        {
                            Id = 19,
                            AnimalId = 19,
                            CageId = 9,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2339),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2339),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2338)
                        },
                        new
                        {
                            Id = 20,
                            AnimalId = 20,
                            CageId = 10,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2341),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2342),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(2341)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Diet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DietName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("TimesPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diets");
                });

            modelBuilder.Entity("Domain.Entities.DietDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DietId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("DietId");

                    b.ToTable("DietDetails");
                });

            modelBuilder.Entity("Domain.Entities.FeedHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FeedingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("TrainerId");

                    b.ToTable("FeedHistories");
                });

            modelBuilder.Entity("Domain.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Domain.Entities.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Habitat")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LifeSpan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WildDiet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9697),
                            Description = "The African lion is a large predatory cat native to Africa.",
                            Habitat = 0,
                            IsDeleted = false,
                            LifeSpan = 10,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9706),
                            Name = "African Lion",
                            ScientificName = "Panthera leo",
                            WildDiet = "Wild antelopes, zebras, and other herbivores"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9709),
                            Description = "The Asian elephant is the largest living land animal in Asia.",
                            Habitat = 1,
                            IsDeleted = false,
                            LifeSpan = 60,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9710),
                            Name = "Asian Elephant",
                            ScientificName = "Elephas maximus",
                            WildDiet = "Grasses, bamboo, fruits, and tree bark"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9712),
                            Description = "The great white shark is a fearsome predator of the oceans.",
                            Habitat = 2,
                            IsDeleted = false,
                            LifeSpan = 70,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9712),
                            Name = "Great White Shark",
                            ScientificName = "Carcharodon carcharias",
                            WildDiet = "Seals, sea lions, fish, and other sharks"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9714),
                            Description = "The European red fox is a cunning and adaptable predator.",
                            Habitat = 3,
                            IsDeleted = false,
                            LifeSpan = 5,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9715),
                            Name = "European Red Fox",
                            ScientificName = "Vulpes vulpes",
                            WildDiet = "Small mammals, birds, fruits, and insects"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9716),
                            Description = "The emperor penguin is the largest penguin species and lives in Antarctica.",
                            Habitat = 4,
                            IsDeleted = false,
                            LifeSpan = 20,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9717),
                            Name = "Emperor Penguin",
                            ScientificName = "Aptenodytes forsteri",
                            WildDiet = "Fish, squid, and krill"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9719),
                            Description = "Kangaroos are marsupials known for their powerful hind legs and pouches.",
                            Habitat = 5,
                            IsDeleted = false,
                            LifeSpan = 6,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9719),
                            Name = "Kangaroo",
                            ScientificName = "Macropus",
                            WildDiet = "Grasses and plants"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9721),
                            Description = "The grizzly bear is a large and formidable North American mammal.",
                            Habitat = 6,
                            IsDeleted = false,
                            LifeSpan = 20,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9722),
                            Name = "Grizzly Bear",
                            ScientificName = "Ursus arctos horribilis",
                            WildDiet = "Fish, berries, roots, and small mammals"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9724),
                            Description = "The polar bear is a marine mammal adapted to the Arctic environment.",
                            Habitat = 4,
                            IsDeleted = false,
                            LifeSpan = 25,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9724),
                            Name = "Polar Bear",
                            ScientificName = "Ursus maritimus",
                            WildDiet = "Seals and fish"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9759),
                            Description = "The Bengal tiger is a majestic big cat native to the Indian subcontinent.",
                            Habitat = 1,
                            IsDeleted = false,
                            LifeSpan = 15,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9759),
                            Name = "Bengal Tiger",
                            ScientificName = "Panthera tigris tigris",
                            WildDiet = "Deer, wild boar, and other ungulates"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9761),
                            Description = "The panda is an iconic bear species known for its bamboo diet.",
                            Habitat = 1,
                            IsDeleted = false,
                            LifeSpan = 20,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 732, DateTimeKind.Local).AddTicks(9762),
                            Name = "Panda",
                            ScientificName = "Ailuropoda melanoleuca",
                            WildDiet = "Bamboo shoots and leaves"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderInformationId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("TicketType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OrderInformationId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.TicketOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TotalMoney")
                        .HasColumnType("float");

                    b.Property<int>("TotalTicket")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TicketOrders");
                });

            modelBuilder.Entity("Domain.Entities.TrainingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1228),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1231),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1219),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 11,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1233),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1234),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1233),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = 2,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1235),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1236),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1235),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = 12,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1238),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1238),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1237),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 5,
                            AnimalId = 3,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1240),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1241),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1239),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 6,
                            AnimalId = 13,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1242),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1243),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1242),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 7,
                            AnimalId = 4,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1244),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1245),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1244),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 8,
                            AnimalId = 14,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1247),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1247),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1246),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 9,
                            AnimalId = 5,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1249),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1250),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1248),
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 10,
                            AnimalId = 15,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1251),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1252),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1251),
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 11,
                            AnimalId = 6,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1253),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1254),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1253),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 12,
                            AnimalId = 16,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1256),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1256),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1255),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 13,
                            AnimalId = 7,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1258),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1258),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1257),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 14,
                            AnimalId = 17,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1260),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1261),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1259),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 15,
                            AnimalId = 8,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1262),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1263),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1262),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 16,
                            AnimalId = 18,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1264),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1265),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1264),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 17,
                            AnimalId = 9,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1267),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1267),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1266),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 18,
                            AnimalId = 19,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1269),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1270),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1269),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 19,
                            AnimalId = 10,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1271),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1272),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1271),
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 20,
                            AnimalId = 20,
                            CreationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1273),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1274),
                            StartDate = new DateTime(2023, 10, 30, 21, 47, 5, 734, DateTimeKind.Local).AddTicks(1273),
                            TrainerId = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.AnimalInformation", b =>
                {
                    b.HasOne("Domain.Entities.Species", "Species")
                        .WithMany("Animals")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Domain.Entities.Cage", b =>
                {
                    b.HasOne("Domain.Entities.Area", "Area")
                        .WithMany("Cages")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Domain.Entities.CageHistory", b =>
                {
                    b.HasOne("Domain.Entities.AnimalInformation", "Animal")
                        .WithMany("CageHistories")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Cage", "Cage")
                        .WithMany("CageHistories")
                        .HasForeignKey("CageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Cage");
                });

            modelBuilder.Entity("Domain.Entities.DietDetail", b =>
                {
                    b.HasOne("Domain.Entities.AnimalInformation", "Animal")
                        .WithMany("DietDetails")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Diet", "Diet")
                        .WithMany("DietDetails")
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Diet");
                });

            modelBuilder.Entity("Domain.Entities.FeedHistory", b =>
                {
                    b.HasOne("Domain.Entities.AnimalInformation", "Animal")
                        .WithMany("FeedHistories")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Account", "Trainer")
                        .WithMany("FeedHistories")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.TicketOrder", "OrderInformation")
                        .WithMany("Tickets")
                        .HasForeignKey("OrderInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderInformation");
                });

            modelBuilder.Entity("Domain.Entities.TrainingDetail", b =>
                {
                    b.HasOne("Domain.Entities.AnimalInformation", "Animal")
                        .WithMany("TrainingDetails")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Account", "Trainer")
                        .WithMany("TrainingDetails")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.Navigation("FeedHistories");

                    b.Navigation("TrainingDetails");
                });

            modelBuilder.Entity("Domain.Entities.AnimalInformation", b =>
                {
                    b.Navigation("CageHistories");

                    b.Navigation("DietDetails");

                    b.Navigation("FeedHistories");

                    b.Navigation("TrainingDetails");
                });

            modelBuilder.Entity("Domain.Entities.Area", b =>
                {
                    b.Navigation("Cages");
                });

            modelBuilder.Entity("Domain.Entities.Cage", b =>
                {
                    b.Navigation("CageHistories");
                });

            modelBuilder.Entity("Domain.Entities.Diet", b =>
                {
                    b.Navigation("DietDetails");
                });

            modelBuilder.Entity("Domain.Entities.Species", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Domain.Entities.TicketOrder", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
