// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20231017164033_Seed Data")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Experiences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 115, DateTimeKind.Local).AddTicks(8571),
                            Fullname = "Lion Tamer",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 115, DateTimeKind.Local).AddTicks(8582),
                            Password = "joUz5qDoLS7mEPrTVtUYot6cLLoVeppbsliABFj0uNsOGoNd",
                            Role = 1,
                            Username = "LionTamer"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 119, DateTimeKind.Local).AddTicks(1467),
                            Fullname = "Pachyderm Pro",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 119, DateTimeKind.Local).AddTicks(1472),
                            Password = "x365ss6RHANrH4zamJS5sigxOr62IBua2bdglUXEASEP1iqN",
                            Role = 1,
                            Username = "PachydermPro"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 122, DateTimeKind.Local).AddTicks(4646),
                            Fullname = "Shark Whisperer",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 122, DateTimeKind.Local).AddTicks(4646),
                            Password = "6AbRCXJ7j6Z/xIQmyo07+1RwHwVZMgZZ5H9vwJsVp81UgoGw",
                            Role = 1,
                            Username = "SharkWhisperer"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 125, DateTimeKind.Local).AddTicks(7151),
                            Fullname = "Fox Friend",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 125, DateTimeKind.Local).AddTicks(7151),
                            Password = "tF10OyzY1YiuXlZyj+AiKAkoJxJZq7iJ2RZpTwr/xLhScno3",
                            Role = 1,
                            Username = "FoxFriend"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 129, DateTimeKind.Local).AddTicks(253),
                            Fullname = "Penguin Pal",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 129, DateTimeKind.Local).AddTicks(254),
                            Password = "fVmO8LkkCFRDpluf1KDiT9Ub0fve/GlZIs4KaeKsENuxUN+t",
                            Role = 1,
                            Username = "PenguinPal"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 132, DateTimeKind.Local).AddTicks(2783),
                            Fullname = "Nhân viên sở thú",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 132, DateTimeKind.Local).AddTicks(2787),
                            Password = "gB2ftD7Sy7PmMeBzUx4+CcuqGU/CB5rITXEeetJI+ZZ9nUsJ",
                            Role = 0,
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("Domain.Entities.AnimalInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("AnimalInformations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2018, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8584),
                            Description = "Majestic African lion named Simba.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8590),
                            Name = "Simba",
                            SpeciesId = 1,
                            Weight = 180.0
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2015, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8670),
                            Description = "Gentle Asian elephant named Dumbo.",
                            Height = 10.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8671),
                            Name = "Dumbo",
                            SpeciesId = 2,
                            Weight = 4500.0
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2017, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8679),
                            Description = "Fearsome great white shark named Jaws.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8679),
                            Name = "Jaws",
                            SpeciesId = 3,
                            Weight = 2000.0
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8684),
                            Description = "Cunning European red fox named Foxy.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8685),
                            Name = "Foxy",
                            SpeciesId = 4,
                            Weight = 10.0
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8690),
                            Description = "Regal emperor penguin named Emmy.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8690),
                            Name = "Emmy",
                            SpeciesId = 5,
                            Weight = 35.0
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2017, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8695),
                            Description = "Energetic kangaroo named Kang.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8696),
                            Name = "Kang",
                            SpeciesId = 6,
                            Weight = 70.0
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2016, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8700),
                            Description = "Majestic grizzly bear named Bear.",
                            Height = 5.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8701),
                            Name = "Bear",
                            SpeciesId = 7,
                            Weight = 800.0
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2015, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8706),
                            Description = "Proud polar bear named Nanook.",
                            Height = 4.5,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8706),
                            Name = "Nanook",
                            SpeciesId = 8,
                            Weight = 900.0
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2016, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8711),
                            Description = "Fierce Bengal tiger named Raja.",
                            Height = 3.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8712),
                            Name = "Raja",
                            SpeciesId = 9,
                            Weight = 200.0
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(2017, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8716),
                            Description = "Adorable panda named Pandy.",
                            Height = 2.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8717),
                            Name = "Pandy",
                            SpeciesId = 10,
                            Weight = 150.0
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8728),
                            Description = "Graceful African lioness named Zara.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8728),
                            Name = "Zara",
                            SpeciesId = 1,
                            Weight = 150.0
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(2016, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8733),
                            Description = "Gentle Asian elephant named Babar.",
                            Height = 9.5,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8734),
                            Name = "Babar",
                            SpeciesId = 2,
                            Weight = 4000.0
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(2018, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8739),
                            Description = "Majestic great white shark named Fins.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8739),
                            Name = "Fins",
                            SpeciesId = 3,
                            Weight = 1800.0
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2021, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8744),
                            Description = "Clever European red fox named Sly.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8744),
                            Name = "Sly",
                            SpeciesId = 4,
                            Weight = 12.0
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(2020, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8749),
                            Description = "Charming emperor penguin named Waddle.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8749),
                            Name = "Waddle",
                            SpeciesId = 5,
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(2017, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8754),
                            Description = "Energetic kangaroo named Joey.",
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8755),
                            Name = "Joey",
                            SpeciesId = 6,
                            Weight = 75.0
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8759),
                            Description = "Playful grizzly bear cub named Bearly.",
                            Height = 2.5,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8760),
                            Name = "Bearly",
                            SpeciesId = 7,
                            Weight = 150.0
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8764),
                            Description = "Young polar bear named Snowy.",
                            Height = 3.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8765),
                            Name = "Snowy",
                            SpeciesId = 8,
                            Weight = 300.0
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8770),
                            Description = "Adventurous Bengal tiger cub named Tyga.",
                            Height = 2.0,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8770),
                            Name = "Tyga",
                            SpeciesId = 9,
                            Weight = 50.0
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(2019, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8775),
                            Description = "Bamboo-loving panda named Bamboo.",
                            Height = 1.5,
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 135, DateTimeKind.Local).AddTicks(8775),
                            Name = "Bamboo",
                            SpeciesId = 10,
                            Weight = 120.0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            Code = "A",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(363),
                            Description = "An exhibit featuring animals from the African savanna",
                            IsDeleted = false,
                            Location = "Savanna Exhibit",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(366),
                            Name = "African Savanna"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 80,
                            Code = "B",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(368),
                            Description = "A lush and diverse rainforest habitat",
                            IsDeleted = false,
                            Location = "Rainforest Pavilion",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(368),
                            Name = "Rainforest"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 50,
                            Code = "C",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(370),
                            Description = "A cold and watery habitat for penguins",
                            IsDeleted = false,
                            Location = "Aquatic Pavilion",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(370),
                            Name = "Penguin Cove"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 60,
                            Code = "D",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(371),
                            Description = "A hot and arid desert environment",
                            IsDeleted = false,
                            Location = "Desert Exhibit",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(372),
                            Name = "Desert Oasis"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 70,
                            Code = "E",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(373),
                            Description = "A vibrant coral reef with colorful fish",
                            IsDeleted = false,
                            Location = "Aquatic Pavilion",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(374),
                            Name = "Tropical Reef"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Cages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            Capacity = 10,
                            Code = "A0001",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1425),
                            Description = "A spacious exhibit featuring African animals.",
                            IsDeleted = false,
                            Location = "Savannah Exhibit",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1428),
                            Name = "African Safari"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            Capacity = 15,
                            Code = "A0002",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1430),
                            Description = "A dedicated area for Asian elephants.",
                            IsDeleted = false,
                            Location = "Asian Elephant Pavilion",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1431),
                            Name = "Elephant Sanctuary"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 2,
                            Capacity = 12,
                            Code = "B0003",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1432),
                            Description = "A large tank showcasing great white sharks.",
                            IsDeleted = false,
                            Location = "Marine World",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1433),
                            Name = "Shark Tank"
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 2,
                            Capacity = 20,
                            Code = "B0004",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1434),
                            Description = "A natural habitat for grizzly bears.",
                            IsDeleted = false,
                            Location = "North American Habitat",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1435),
                            Name = "Grizzly Wilderness"
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 3,
                            Capacity = 8,
                            Code = "C0005",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1436),
                            Description = "A chilly paradise for emperor penguins.",
                            IsDeleted = false,
                            Location = "Antarctic Exhibit",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1436),
                            Name = "Penguin Paradise"
                        },
                        new
                        {
                            Id = 6,
                            AreaId = 1,
                            Capacity = 20,
                            Code = "A0006",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1438),
                            Description = "A vast exhibit showcasing African wildlife.",
                            IsDeleted = false,
                            Location = "Wide Open Savannah",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1438),
                            Name = "African Plains"
                        },
                        new
                        {
                            Id = 7,
                            AreaId = 2,
                            Capacity = 18,
                            Code = "B0007",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1440),
                            Description = "A chilly environment for polar animals.",
                            IsDeleted = false,
                            Location = "Arctic Enclosure",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1440),
                            Name = "Polar Icecaps"
                        },
                        new
                        {
                            Id = 8,
                            AreaId = 3,
                            Capacity = 12,
                            Code = "C0008",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1442),
                            Description = "An arid landscape for Australian fauna.",
                            IsDeleted = false,
                            Location = "Australian Habitat",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1442),
                            Name = "Aussie Outback"
                        },
                        new
                        {
                            Id = 9,
                            AreaId = 4,
                            Capacity = 15,
                            Code = "D0009",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1443),
                            Description = "A dense forest for Siberian wildlife.",
                            IsDeleted = false,
                            Location = "Russian Wilderness",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1444),
                            Name = "Siberian Taiga"
                        },
                        new
                        {
                            Id = 10,
                            AreaId = 5,
                            Capacity = 25,
                            Code = "E0010",
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1445),
                            Description = "A lush jungle exhibit for Amazon species.",
                            IsDeleted = false,
                            Location = "South American Jungle",
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(1446),
                            Name = "Amazon Rainforest"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("CageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("CageId");

                    b.ToTable("CageHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            CageId = 1,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3919),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3920),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3916)
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 2,
                            CageId = 2,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3921),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3922),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3921)
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = 3,
                            CageId = 3,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3923),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3924),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3923)
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = 4,
                            CageId = 4,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3925),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3925),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3925)
                        },
                        new
                        {
                            Id = 5,
                            AnimalId = 5,
                            CageId = 5,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3927),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3927),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3926)
                        },
                        new
                        {
                            Id = 6,
                            AnimalId = 6,
                            CageId = 6,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3929),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3929),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3928)
                        },
                        new
                        {
                            Id = 7,
                            AnimalId = 7,
                            CageId = 7,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3930),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3931),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3930)
                        },
                        new
                        {
                            Id = 8,
                            AnimalId = 8,
                            CageId = 8,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3932),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3933),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3932)
                        },
                        new
                        {
                            Id = 9,
                            AnimalId = 9,
                            CageId = 9,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3934),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3934),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3933)
                        },
                        new
                        {
                            Id = 10,
                            AnimalId = 10,
                            CageId = 10,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3936),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3936),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3935)
                        },
                        new
                        {
                            Id = 11,
                            AnimalId = 11,
                            CageId = 1,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3937),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3938),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3937)
                        },
                        new
                        {
                            Id = 12,
                            AnimalId = 12,
                            CageId = 2,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3939),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3940),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3939)
                        },
                        new
                        {
                            Id = 13,
                            AnimalId = 13,
                            CageId = 3,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3941),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3941),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3941)
                        },
                        new
                        {
                            Id = 14,
                            AnimalId = 14,
                            CageId = 4,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3943),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3943),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3942)
                        },
                        new
                        {
                            Id = 15,
                            AnimalId = 15,
                            CageId = 5,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3944),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3945),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3944)
                        },
                        new
                        {
                            Id = 16,
                            AnimalId = 16,
                            CageId = 6,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3946),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3947),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3946)
                        },
                        new
                        {
                            Id = 17,
                            AnimalId = 17,
                            CageId = 7,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3948),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3948),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3948)
                        },
                        new
                        {
                            Id = 18,
                            AnimalId = 18,
                            CageId = 8,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3950),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3950),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3949)
                        },
                        new
                        {
                            Id = 19,
                            AnimalId = 19,
                            CageId = 9,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3952),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3952),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3951)
                        },
                        new
                        {
                            Id = 20,
                            AnimalId = 20,
                            CageId = 10,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3953),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3954),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(3953)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Diet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DietName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("TimesPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diets");
                });

            modelBuilder.Entity("Domain.Entities.DietDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DietId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("DietId");

                    b.ToTable("DietDetails");
                });

            modelBuilder.Entity("Domain.Entities.FeedHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FeedingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("TrainerId");

                    b.ToTable("FeedHistories");
                });

            modelBuilder.Entity("Domain.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Domain.Entities.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Habitat")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LifeSpan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WildDiet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9868),
                            Description = "The African lion is a large predatory cat native to Africa.",
                            Habitat = 0,
                            IsDeleted = false,
                            LifeSpan = 10,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9874),
                            Name = "African Lion",
                            ScientificName = "Panthera leo",
                            WildDiet = "Wild antelopes, zebras, and other herbivores"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9876),
                            Description = "The Asian elephant is the largest living land animal in Asia.",
                            Habitat = 1,
                            IsDeleted = false,
                            LifeSpan = 60,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9877),
                            Name = "Asian Elephant",
                            ScientificName = "Elephas maximus",
                            WildDiet = "Grasses, bamboo, fruits, and tree bark"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9878),
                            Description = "The great white shark is a fearsome predator of the oceans.",
                            Habitat = 2,
                            IsDeleted = false,
                            LifeSpan = 70,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9879),
                            Name = "Great White Shark",
                            ScientificName = "Carcharodon carcharias",
                            WildDiet = "Seals, sea lions, fish, and other sharks"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9880),
                            Description = "The European red fox is a cunning and adaptable predator.",
                            Habitat = 3,
                            IsDeleted = false,
                            LifeSpan = 5,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9881),
                            Name = "European Red Fox",
                            ScientificName = "Vulpes vulpes",
                            WildDiet = "Small mammals, birds, fruits, and insects"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9882),
                            Description = "The emperor penguin is the largest penguin species and lives in Antarctica.",
                            Habitat = 4,
                            IsDeleted = false,
                            LifeSpan = 20,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9882),
                            Name = "Emperor Penguin",
                            ScientificName = "Aptenodytes forsteri",
                            WildDiet = "Fish, squid, and krill"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9884),
                            Description = "Kangaroos are marsupials known for their powerful hind legs and pouches.",
                            Habitat = 5,
                            IsDeleted = false,
                            LifeSpan = 6,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9884),
                            Name = "Kangaroo",
                            ScientificName = "Macropus",
                            WildDiet = "Grasses and plants"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9886),
                            Description = "The grizzly bear is a large and formidable North American mammal.",
                            Habitat = 6,
                            IsDeleted = false,
                            LifeSpan = 20,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9886),
                            Name = "Grizzly Bear",
                            ScientificName = "Ursus arctos horribilis",
                            WildDiet = "Fish, berries, roots, and small mammals"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9887),
                            Description = "The polar bear is a marine mammal adapted to the Arctic environment.",
                            Habitat = 4,
                            IsDeleted = false,
                            LifeSpan = 25,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9888),
                            Name = "Polar Bear",
                            ScientificName = "Ursus maritimus",
                            WildDiet = "Seals and fish"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9889),
                            Description = "The Bengal tiger is a majestic big cat native to the Indian subcontinent.",
                            Habitat = 1,
                            IsDeleted = false,
                            LifeSpan = 15,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9890),
                            Name = "Bengal Tiger",
                            ScientificName = "Panthera tigris tigris",
                            WildDiet = "Deer, wild boar, and other ungulates"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9891),
                            Description = "The panda is an iconic bear species known for its bamboo diet.",
                            Habitat = 1,
                            IsDeleted = false,
                            LifeSpan = 20,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 136, DateTimeKind.Local).AddTicks(9892),
                            Name = "Panda",
                            ScientificName = "Ailuropoda melanoleuca",
                            WildDiet = "Bamboo shoots and leaves"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderInformationId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OrderInformationId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.TicketOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TotalMoney")
                        .HasColumnType("float");

                    b.Property<int>("TotalTicket")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TicketOrders");
                });

            modelBuilder.Entity("Domain.Entities.TrainingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8086),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8089),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8078),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 11,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8090),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8091),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8090),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = 2,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8092),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8093),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8092),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = 12,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8094),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8094),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8094),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 5,
                            AnimalId = 3,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8096),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8096),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8095),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 6,
                            AnimalId = 13,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8098),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8098),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8097),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 7,
                            AnimalId = 4,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8099),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8100),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8099),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 8,
                            AnimalId = 14,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8101),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8102),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8101),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 9,
                            AnimalId = 5,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8103),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8103),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8103),
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 10,
                            AnimalId = 15,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8105),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8105),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8104),
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 11,
                            AnimalId = 6,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8106),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8107),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8106),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 12,
                            AnimalId = 16,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8108),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8109),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8108),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 13,
                            AnimalId = 7,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8110),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8110),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8110),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 14,
                            AnimalId = 17,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8112),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8112),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8111),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 15,
                            AnimalId = 8,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8114),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8114),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8113),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 16,
                            AnimalId = 18,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8115),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8116),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8115),
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 17,
                            AnimalId = 9,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8117),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8117),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8117),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 18,
                            AnimalId = 19,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8119),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8119),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8118),
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 19,
                            AnimalId = 10,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8120),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8121),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8120),
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 20,
                            AnimalId = 20,
                            CreationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8122),
                            IsDeleted = false,
                            ModificationDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8123),
                            StartDate = new DateTime(2023, 10, 17, 23, 40, 33, 137, DateTimeKind.Local).AddTicks(8122),
                            TrainerId = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.AnimalInformation", b =>
                {
                    b.HasOne("Domain.Entities.Species", "Species")
                        .WithMany("Animals")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Domain.Entities.Cage", b =>
                {
                    b.HasOne("Domain.Entities.Area", "Area")
                        .WithMany("Cages")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Domain.Entities.CageHistory", b =>
                {
                    b.HasOne("Domain.Entities.AnimalInformation", "Animal")
                        .WithMany("CageHistories")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Cage", "Cage")
                        .WithMany("CageHistories")
                        .HasForeignKey("CageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Cage");
                });

            modelBuilder.Entity("Domain.Entities.DietDetail", b =>
                {
                    b.HasOne("Domain.Entities.AnimalInformation", "Animal")
                        .WithMany("DietDetails")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Diet", "Diet")
                        .WithMany("DietDetails")
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Diet");
                });

            modelBuilder.Entity("Domain.Entities.FeedHistory", b =>
                {
                    b.HasOne("Domain.Entities.AnimalInformation", "Animal")
                        .WithMany("FeedHistories")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Account", "Trainer")
                        .WithMany("FeedHistories")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.TicketOrder", "OrderInformation")
                        .WithMany("Tickets")
                        .HasForeignKey("OrderInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderInformation");
                });

            modelBuilder.Entity("Domain.Entities.TrainingDetail", b =>
                {
                    b.HasOne("Domain.Entities.AnimalInformation", "Animal")
                        .WithMany("TrainingDetails")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Account", "Trainer")
                        .WithMany("TrainingDetails")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.Navigation("FeedHistories");

                    b.Navigation("TrainingDetails");
                });

            modelBuilder.Entity("Domain.Entities.AnimalInformation", b =>
                {
                    b.Navigation("CageHistories");

                    b.Navigation("DietDetails");

                    b.Navigation("FeedHistories");

                    b.Navigation("TrainingDetails");
                });

            modelBuilder.Entity("Domain.Entities.Area", b =>
                {
                    b.Navigation("Cages");
                });

            modelBuilder.Entity("Domain.Entities.Cage", b =>
                {
                    b.Navigation("CageHistories");
                });

            modelBuilder.Entity("Domain.Entities.Diet", b =>
                {
                    b.Navigation("DietDetails");
                });

            modelBuilder.Entity("Domain.Entities.Species", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Domain.Entities.TicketOrder", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
